### ISSUE TITLE
Reduce Sign Up Page height

### ISSUE THREAD

**Issue by theobiabo** [Bookhive-Club/Bookhive-Client#10]
The Input Field side on signup screen is making the page scroll

#### TODO 

* You need to Adjust it, to prevent the page from ading a scrollbar. 
* It should be fitted on the page
* Remove the phone number input

Path on the applicatoin /auth/signup
path on github [View page](https://github.com/Bookhive-Club/Bookhive-Client/blob/main/src/app/auth/signup/page.tsx)

**Comment by Sayan2908** [comment]
Hey there can I work on this issue I would be happy to help

**Comment by theobiabo** [comment]
Yea sure assigning it to you

**Comment by Sayan2908** [comment]
I have reduced the size now there is no scrolling

![Screenshot 2023-10-04 164544](https://github.com/Bookhive-Club/Bookhive-Client/assets/107147382/c73a4f58-7f50-4de4-a980-f477171e7b1b)

**Comment by theobiabo** [comment]
awesome, but you can leave the heigh as it is. just remove the phone number input there. 

  and everything will look okay.

**Comment by theobiabo** [comment]
leave the height of the inputs as it is. Just remove the phone number input. we dont need it.

also dont forget to remove it from the validation schema from here 
https://github.com/Bookhive-Club/Bookhive-Client/blob/main/src/validations/auth/signupValidationSchema.ts

and also on the initialValue of formik from the signup
