### ISSUE TITLE
Issue while referring to Contribution Guidelines. 

### ISSUE THREAD

**Issue by suresh33661** [Bookhive-Club/Bookhive-Client#12]
- [x] There is an error referring to [contribution Guidelines](https://github.com/Bookhive-Club/Bookhive-Client/blob/main/CONTRIBUTING.md) from the Readme file.
![Screenshot 2023-10-04 153145](https://github.com/Bookhive-Club/Bookhive-Client/assets/132880363/a9eaed18-9d27-4701-a7fa-41b3a24b3501)

**Comment by theobiabo** [comment]
hey @suresh33661 thanks for this. 

 you can actually work on that. mind if i assign it to you??

**Comment by suresh33661** [comment]
Hi can you label it for hactoberfest.

**Comment by theobiabo** [comment]
just did

**Comment by theobiabo** [comment]
dont forget to give the repo a star
