### ISSUE TITLE
Centeralize Auth page vertically

### ISSUE THREAD

**Issue by theobiabo** [Bookhive-Club/Bookhive-Client#18]
#### Centralize form item vertically 

* Make the form item to be align-item center
* The form item should be verically aligned center on desktop 

### Current View 
👇🏾👇🏾

![Screenshot from 2023-10-10 12-21-15](https://github.com/Bookhive-Club/Bookhive-Client/assets/54102389/924b95e9-1cc1-45fa-b15f-47f54bb1f45a)

Form item on the left should be veritically aligned center

**Comment by DylanP97** [comment]
Hey, I can do this and I would love too!
Please assign me to it ;)

**Comment by theobiabo** [comment]
Awesome. I will assign it to you now

**Comment by Virtual4087** [comment]
Assign me

**Comment by theobiabo** [comment]
> Assign me

Already assign to @DylanP97

**Comment by Virtual4087** [comment]
> > Assign me
> 
> Already assign to @DylanP97

ohh my bad i didn't see it and opened a pr you can close it

**Comment by DylanP97** [comment]
I just sent a PR ;) let me know if everything's alright

**Comment by theobiabo** [comment]
Seen and approved, nice work man.

  Next time, add a screenshoot, to what you fixed, in the PR to aid the reviewer

**Comment by DylanP97** [comment]
Alright noted
Thanks for the opportunity

**Comment by theobiabo** [comment]
Creating more issues. you can stay in touch and dont forget to give the repo a star
