### ISSUE TITLE
Design Footer for homepage

### ISSUE THREAD

**Issue by theobiabo** [Bookhive-Club/Bookhive-Client#29]
#### Design footer for homepage

- Footer should be responsive across Mobile, Tablets and Desktop 
- Footer should be easy like this desktop 👇👇👇
![Screenshot from 2023-10-20 14-18-57](https://github.com/Bookhive-Club/Bookhive-Client/assets/54102389/310eb665-e4b2-47ec-8a53-341ce91fcfdc)

and look like this on mobile 👇👇👇
![Screenshot from 2023-10-20 14-19-22](https://github.com/Bookhive-Club/Bookhive-Client/assets/54102389/e20c9278-d874-4d3f-aad1-061d90e7a49b)

NB: Pull from Dev and Raise a PR to Dev

**Comment by anyahush** [comment]
Would like to do this, can you assign to me?

**Comment by theobiabo** [comment]
Yea sure

**Comment by theobiabo** [comment]
I just assigned it to you

**Comment by theobiabo** [comment]
The Footer code is located at src/components/atom/home/footer.tsx

![Screenshot from 2023-10-20 17-56-58](https://github.com/Bookhive-Club/Bookhive-Client/assets/54102389/59c5b17e-2ae3-40fe-b3fb-aaee575a396c)

**Comment by Nishanth019** [comment]
I will work on this issue; please assign it to me.

**Comment by theobiabo** [comment]
Thanks alot, but it has already been assigned to @anyahush

**Comment by anyahush** [comment]
@yhoungdev really sorry something has come up. Won't be able to work on this right now, happy if you want to reassign. Sorry!

**Comment by theobiabo** [comment]
ok no problem @anyahush, please @Nishanth019 are you still up for it ?
