### ISSUE TITLE
Broken markdown syntax for folder structure

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [Bookhive-Club/Bookhive-Client#4]
Hi @yhoungdev,

The folder structure section in the README is broken. I'd love to fix it.

![Screenshot_20230703_141747_Chrome](https://github.com/Bookhive-Club/Bookhive-Client/assets/48127194/722e25f8-9308-4ffd-a7b2-4ad1b09912c3)

**Comment by theobiabo** [comment]
No problem you can go ahead
