### ISSUE TITLE
[Bug] Overflow-x Issue on Mobile View in Landing Page

### ISSUE THREAD

**Issue by dev-phantom** [Bookhive-Club/Bookhive-Client#6]
### Issue Description
When viewing the landing page on mobile devices, there is an overflow-x issue that causes horizontal scrolling. This disrupts the user experience and should be addressed to ensure a seamless mobile browsing experience.

### Steps to Reproduce
1. Access the landing page on a mobile device.
2. Observe that horizontal scrolling is possible, indicating an overflow-x issue.

### Expected Behavior
The landing page should adapt to the screen size of mobile devices and prevent horizontal scrolling.

### Actual Behavior
Horizontal scrolling is possible on the landing page when viewed on mobile devices.

### Environment
- Device: Tecno spark 4 
- Browser: chrome 

### Screenshots

https://github.com/Bookhive-Club/Bookhive-Client/assets/72051159/74f86cea-e8b1-43c0-9b58-014dfea7c217

### Labels
- bug
- mobile
- overflow-x

Please prioritize this issue as it affects the user experience on mobile devices.

**Comment by theobiabo** [comment]
Awesome, thanks for this

**Comment by theobiabo** [comment]
hey @dev-phantom have you been able to resolve this ? if no i can point out some of the issue.

**Comment by dev-phantom** [comment]
Sorry for the delay on this

Please feel free to point them out

**Comment by theobiabo** [comment]
ok boss

**Comment by theobiabo** [comment]
hi @dev-phantom good day sir, are you still working on this ?

**Comment by dev-phantom** [comment]
> hi @dev-phantom good day sir, are you still working on this ? 

No sir,
I'm sorry for the inconvenience, but I won't be able to fix this issue promptly due to upcoming school exams. If you prefer, the maintainer can unassign me. Thanks for your understanding.

**Comment by theobiabo** [comment]
Ok. K problem boss
