### ISSUE TITLE
[Feat] Limited Issue Creation Options - Missing Bug and Other Categories

### ISSUE THREAD

**Issue by dev-phantom** [Bookhive-Club/Bookhive-Client#7]
### Issue Description
When attempting to create a new issue in this repository, there is only an option for a "feat request." This limitation is causing inconvenience for users who need to report bugs, request support, or submit other types of issues. We should provide a broader set of issue categories to cater to various types of user feedback and requests.

### Steps to Reproduce
1. Navigate to the "New Issue" page in this repository.
2. Observe that the only available issue category is "feat request."

### Expected Behavior
Users should have the option to select from a range of issue categories, including bug reports, feature requests, support requests, and others, based on their needs.

### Actual Behavior
Only the "feat request" category is available when creating a new issue, limiting the types of issues that can be reported.

### Proposed Solution
1. Add additional issue categories such as:
   - Bug report
   - Support request
   - Documentation issue
   - Enhancement request
   - Other (with a text field for custom issue types)

2. Ensure that users can easily categorize their issues to provide more clarity.

### Labels
- issue creation
- enhancement
- user experience

This enhancement will improve the user experience and help us better organize and prioritize incoming issues.

**Comment by theobiabo** [comment]
Thanks alot for this. for now you can only create feature requrest and blank issues. 

  thanks for noting this up i will include those to the ISSUE_TEMPLATE by Gods grace
